#!/bin/bash

echo ------ removing image ------ 1/3.
dr rmi -f my-generator
echo ------ building image ------ 2/3.
docker build --rm -t my-generator .
echo ------ running image  ------ 3/3.
dr rm my-generator
dr run -p 5000:5000 \
     --link my-virtuoso:database \
     -e MODE=development \
     --volume=/home/sam/PycharmProjects/my-generator/:/app \
     --name "my-generator" my-generator

